import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar / shell
    "nav.home": "Home",
    "nav.properties": "Properties",
    "nav.myProperties": "My Properties",
    "nav.addProperty": "Add Property",
    "nav.bookings": "Bookings",
    "nav.favorites": "Favorites",
    "nav.messages": "Messages",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "nav.register": "Register",
    "footer.text": "© 2026 Home Rental System. Crafted for modern rentals.",
    "footer.tagline": "Find your next home or rent out your space with ease.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "common.loading": "Loading...",

    // Home
    "home.tagline": "Modern rentals, faster decisions",
    "home.title": "Discover the perfect rental in one place.",
    "home.subtitle":
      "Browse premium apartments, houses, and landlord-managed rentals with listings designed for trust, speed, and simplicity.",
    "home.browse": "Browse Properties",
    "home.stats.properties": "Properties Listed",
    "home.stats.tenants": "Happy Tenants",
    "home.stats.cities": "Cities Covered",
    "home.stats.landlords": "Trusted Landlords",
    "home.how.title": "How It Works",
    "home.how.step1": "Search & Compare",
    "home.how.step1.desc": "Browse verified listings with photos, maps, and clear pricing.",
    "home.how.step2": "Book a Viewing",
    "home.how.step2.desc": "Request a viewing and message the landlord directly.",
    "home.how.step3": "Move In",
    "home.how.step3.desc": "Sign the digital agreement and collect your keys.",
    "home.featured.title": "Featured Properties",
    "home.cta.title": "Are you a landlord?",
    "home.cta.desc": "List your property and reach thousands of verified tenants.",
    "home.cta.button": "List Your Property",
    "home.getStarted": "Get Started",
    "home.quickTitle": "Find the right home fast",
    "home.location": "Location",
    "home.maxPrice": "Max Price",
    "home.bedrooms": "Bedrooms",
    "home.search": "Search",
    "home.whyTitle": "Why choose Home Rental?",
    "home.verified.title": "Verified Listings",
    "home.verified.desc":
      "Every property is reviewed for quality and accuracy before it appears in search results.",
    "home.smart.title": "Smart Search",
    "home.smart.desc":
      "Filter by price, location, bedrooms, and features to find the home that fits your needs.",
    "home.secure.title": "Secure Experience",
    "home.secure.desc":
      "Secure accounts, protected listings, and easy property management for owners and tenants.",

    // Auth
    "login.title": "Log in to your account",
    "login.subtitle":
      "Access your dashboard, saved properties, and rental bookings.",
    "login.forgot": "Forgot password?",
    "login.button": "Login",
    "login.loading": "Logging in...",
    "login.noAccount": "Don't have an account?",
    "login.createOne": "Create one",
    "register.title": "Create your account",
    "register.subtitle":
      "Register as a tenant or landlord and start managing rentals today.",
    "register.tenant": "Tenant",
    "register.landlord": "Landlord",
    "register.button": "Create account",
    "register.loading": "Registering...",
    "register.success": "Registration successful!",
    "register.haveAccount": "Already have an account?",
    "register.logIn": "Log in",
    "form.email": "Email",
    "form.password": "Password",
    "form.fullName": "Full Name",
    "form.phone": "Phone Number",
    "forgot.title": "Forgot password",
    "forgot.button": "Send reset link",
    "forgot.devLink": "Dev reset link:",
    "reset.title": "Reset password",
    "reset.newPassword": "New password",
    "reset.button": "Reset password",
    "verify.title": "Verify email",

    // Properties list
    "properties.title": "Available Properties",
    "properties.searchPlaceholder": "Search by title, city, area...",
    "properties.allTypes": "All Types",
    "properties.anyBedrooms": "Any Bedrooms",
    "properties.bedroomsMin": "Bedrooms",
    "properties.sort.newest": "Newest First",
    "properties.sort.oldest": "Oldest First",
    "properties.sort.priceAsc": "Price: Low to High",
    "properties.sort.priceDesc": "Price: High to Low",
    "properties.minPrice": "Min Price (ETB)",
    "properties.maxPrice": "Max Price (ETB)",
    "properties.search": "Search",
    "properties.reset": "Reset",
    "properties.found": "properties found",
    "properties.foundOne": "property found",
    "properties.none": "No properties found.",
    "properties.prev": "Prev",
    "properties.next": "Next",
    "properties.viewDetails": "View Details",
    "properties.edit": "Edit",
    "properties.delete": "Delete",
    "properties.rented": "Rented",
    "properties.confirmDelete": "Are you sure you want to delete this property?",

    // Property types
    "type.Apartment": "Apartment",
    "type.Villa": "Villa",
    "type.House": "House",
    "type.Studio": "Studio",
    "type.Condominium": "Condominium",
    "type.Office": "Office",
    "type.Commercial Space": "Commercial Space",
    "type.Hostel": "Hostel",
    "type.Shared Room": "Shared Room",
    "type.Guest House": "Guest House",

    // Property details
    "details.bedrooms": "Bedrooms",
    "details.bathrooms": "Bathrooms",
    "details.area": "Area",
    "details.description": "Description",
    "details.amenities": "Amenities",
    "details.ownerInfo": "Owner Information",
    "details.name": "Name",
    "details.email": "Email",
    "details.phone": "Phone",
    "details.verified": "Verified",
    "details.contactOwner": "Contact Owner",
    "details.contactPlaceholder": "Write your message to the owner...",
    "details.send": "Send",
    "details.messageSent": "Message sent to the owner.",
    "details.report": "Report Property",
    "details.selectReason": "Select a reason",
    "details.reasonFake": "Fake property",
    "details.reasonIncorrect": "Incorrect information",
    "details.reasonFraud": "Fraudulent landlord",
    "details.reasonScam": "Scam",
    "details.reasonInappropriate": "Inappropriate content",
    "details.reasonOther": "Other",
    "details.reportPlaceholder": "Describe the issue (optional)",
    "details.submitReport": "Submit Report",
    "details.reportSuccess": "Report submitted. Our team will review it.",
    "details.mapLocation": "Map Location",
    "details.perMonth": "/month",
    "details.requestViewing": "Request a Viewing",
    "details.messagePlaceholder": "Message to the owner (optional)",
    "details.sendRequest": "Send Viewing Request",
    "details.ownProperty": "This is your property.",
    "details.editIt": "Edit it",
    "details.orManage": "or manage viewing requests on the",
    "details.bookingsPage": "Bookings page",
    "details.reviews": "Reviews",
    "details.writeReview": "Write a review",
    "details.reviewPlaceholder": "Share your experience with this property...",
    "details.submitReview": "Submit Review",
    "details.delete": "Delete",
    "details.save": "Save",
    "details.saved": "Saved",
    "details.noReviews": "No reviews yet. Be the first!",
    "details.loginTo": "Log in",
    "details.loginToDesc": "to write a review or request a viewing.",
    "details.notFound": "Property not found.",

    // Amenities
    "amenity.Furnished": "Furnished",
    "amenity.Parking": "Parking",
    "amenity.Internet": "Internet",
    "amenity.Balcony": "Balcony",
    "amenity.Garden": "Garden",
    "amenity.Swimming Pool": "Swimming Pool",
    "amenity.Security": "Security",
    "amenity.Pets Allowed": "Pets Allowed",

    // Add / Edit property
    "add.title": "Add Property",
    "add.propertyTitle": "Property Title",
    "add.description": "Description",
    "add.price": "Price",
    "add.location": "Location",
    "add.bedrooms": "Bedrooms",
    "add.bathrooms": "Bathrooms",
    "add.area": "Area (m²)",
    "add.propertyType": "Property Type",
    "add.photos": "Photos (up to 5)",
    "add.button": "Add Property",
    "add.uploading": "Uploading images...",
    "add.saving": "Saving property...",
    "add.success": "Property added successfully!",
    "edit.title": "Edit Property",
    "edit.button": "Save Changes",
    "edit.success": "Property updated successfully!",

    // My properties
    "my.title": "My Properties",
    "my.empty": "You haven't added any properties yet.",
    "my.confirmDelete": "Delete this property?",

    // Dashboard
    "dash.title": "Dashboard",
    "dash.welcome": "Welcome",
    "dash.email": "Email",
    "dash.role": "Role",
    "dash.overview": "Overview",
    "dash.favorites": "Saved Favorites",
    "dash.viewingRequests": "Viewing Requests",
    "dash.myProperties": "My Properties",
    "dash.pendingRequests": "Pending Requests",
    "dash.reviewsWritten": "Reviews Written",
    "dash.loadingStats": "Loading stats...",
    "dash.adminOverview": "Admin Overview",
    "dash.totalUsers": "Total Users",
    "dash.landlords": "Landlords",
    "dash.activeProperties": "Active / Total Properties",
    "dash.totalReviews": "Total Reviews",
    "dash.pendingViewings": "Pending Viewing Requests",
    "dash.recentUsers": "Recent Users",
    "dash.name": "Name",
    "dash.joined": "Joined",
    "dash.notLoggedIn": "You are not logged in.",
    "dash.quickActions": "Quick Actions",
    "dash.yourProperties": "Your Properties",
    "dash.manageAll": "Manage all",
    "dash.noProperties": "You haven't listed any properties yet.",
    "dash.pendingApproval": "Pending approval",
    "dash.viewRequests": "Review booking requests",
    "dash.recentRequests": "Recent Viewing Requests",
    "dash.viewAll": "View all",
    "dash.noRequests": "You have no viewing requests yet.",
    "dash.recommended": "Recommended for You",

    // Bookings
    "bookings.title": "Viewing Requests",
    "bookings.myRequests": "My Requests",
    "bookings.receivedRequests": "Received Requests",
    "bookings.none": "You have not requested any viewings yet.",
    "bookings.browse": "Browse properties",
    "bookings.noneReceived": "No viewing requests on your properties yet.",
    "bookings.cancel": "Cancel",
    "bookings.approve": "Approve",
    "bookings.reject": "Reject",
    "bookings.requestedBy": "Requested by",
    "bookings.owner": "Owner",
    "bookings.propertyRemoved": "Property removed",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.cancelled": "Cancelled",

    // Favorites
    "favorites.title": "My Favorites",
    "favorites.empty": "You have not saved any properties yet.",

    // Messages
    "messages.title": "Messages",
    "messages.loading": "Loading...",
    "messages.empty": "No conversations yet.",
    "messages.unread": "new",
    "messages.placeholder": "Type a message...",
    "messages.send": "Send",

    // Admin
    "admin.users": "Manage Users",
    "admin.properties": "Manage Properties",
    "admin.reports": "Reports",
    "admin.searchUsers": "Search by name or email",
    "admin.allRoles": "All roles",
    "admin.allStatuses": "All statuses",
    "admin.filter": "Filter",
    "admin.status": "Status",
    "admin.actions": "Actions",
    "admin.active": "Active",
    "admin.suspended": "Suspended",
    "admin.suspend": "Suspend",
    "admin.activate": "Activate",
    "admin.delete": "Delete",
    "admin.deleteConfirm": "Delete user",
    "admin.deletePropertyConfirm": "Delete this property?",
    "admin.approve": "Approve",
    "admin.markPending": "Pending",
    "admin.deactivate": "Deactivate",
    "admin.inactive": "Inactive",
    "admin.title": "Title",
    "admin.owner": "Owner",
    "admin.price": "Price",
    "admin.noReports": "No reports submitted yet.",
    "admin.reportedBy": "Reported by",
    "admin.property": "Property",
    "admin.user": "User",
    "admin.reason": "Reason",
    "admin.resolve": "Resolve",
    "admin.dismiss": "Dismiss",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAll": "Mark all read",
    "notifications.empty": "No notifications yet.",

    // Payments
    "payments.payNow": "Pay Now",
    "payments.title": "Complete Payment",
    "payments.method": "Payment Method",
    "payments.bankTransfer": "Bank Transfer",
    "payments.card": "Card Payment",
    "payments.cash": "Cash",
    "payments.confirm": "Confirm Payment",
    "payments.cancel": "Cancel",
    "payments.success": "Payment successful!",
    "payments.pageTitle": "Payments",
    "payments.myMethods": "My Payment Methods",
    "payments.methodsHint": "Tenants pay into one of these accounts, then upload a screenshot for your approval.",
    "payments.addMethod": "Add Method",
    "payments.saveMethods": "Save Methods",
    "payments.methodsSaved": "Payment methods saved.",
    "payments.labelPh": "Label (e.g. Telebirr)",
    "payments.accountName": "Account / Holder Name",
    "payments.accountNumber": "Account / Phone Number",
    "payments.received": "Received Payments",
    "payments.myPayments": "My Payments",
    "payments.noPayments": "No payments yet.",
    "payments.approve": "Approve",
    "payments.reject": "Reject",
    "payments.rejectReason": "Reason for rejection (optional)",
    "payments.viewShot": "View proof",
    "payments.pendingApproval": "Awaiting landlord approval",
    "payments.noMethods": "The landlord has not added any payment methods yet.",
    "payments.uploadShot": "Payment screenshot (proof)",
    "payments.submitProof": "Submit Payment Proof",
    "payments.submitted": "Payment proof submitted. Waiting for landlord approval.",
    "payments.needShot": "Please attach a payment screenshot.",
    "payments.viewFirst": "View the payment screenshot first",

    // Agreement
    "agreement.view": "View Agreement",
    "agreement.title": "Rental Agreement",
    "agreement.print": "Print",
    "agreement.generated": "Generated",
    "agreement.tenant": "Tenant",
    "agreement.landlord": "Landlord",
    "agreement.property": "Property",
    "agreement.terms": "Terms & Conditions",
    "agreement.startDate": "Start Date",
    "agreement.monthlyRent": "Monthly Rent",
    "agreement.deposit": "Deposit",
    "agreement.tenantSignature": "Tenant Signature",
    "agreement.landlordSignature": "Landlord Signature",

    // Profile
    "profile.title": "Your Profile",
    "profile.address": "Address",
    "profile.bio": "Short bio",
    "profile.avatar": "Profile avatar",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
  },

  am: {
    // Navbar / shell
    "nav.home": "መነሻ",
    "nav.properties": "ቤቶች",
    "nav.myProperties": "የእኔ ቤቶች",
    "nav.addProperty": "ቤት ጨምር",
    "nav.bookings": "ቀጠሮዎች",
    "nav.favorites": "ተወዳጆች",
    "nav.messages": "መልእክቶች",
    "nav.dashboard": "ዳሽቦርድ",
    "nav.profile": "መገለጫ",
    "nav.logout": "ውጣ",
    "nav.login": "ግባ",
    "nav.register": "ተመዝገብ",
    "footer.text": "© 2026 የቤት ኪራይ ሲስተም። ለዘመናዊ ኪራይ የተሰራ።",
    "footer.tagline": "ቀጣዩን ቤትዎን ያግኙ ወይም ቦታዎን በቀላሉ ያከራዩ።",
    "footer.quickLinks": "ፈጣን አገናኞች",
    "footer.contact": "ያግኙን",
    "footer.rights": "መብቱ በህግ የተጠበቀ ነው።",
    "common.loading": "በመጫን ላይ...",

    // Home
    "home.tagline": "ዘመናዊ ኪራዮች፣ ፈጣን ውሳኔዎች",
    "home.title": "ፍጹም የኪራይ ቤት በአንድ ቦታ ያግኙ።",
    "home.subtitle":
      "ለአደራ፣ ለፍጥነት እና ለቀላልነት የተነደፉ ዝርዝሮች ያሏቸውን ምርጥ አፓርታማዎችን፣ ቤቶችን እና በባለቤት የሚተዳደሩ ኪራዮችን ይመልከቱ።",
    "home.browse": "ቤቶችን ይመልከቱ",
    "home.stats.properties": "የተዘረዘሩ ቤቶች",
    "home.stats.tenants": "ደስተኛ ተራዮች",
    "home.stats.cities": "የተሸፈኑ ተሞች",
    "home.stats.landlords": "የታመኑ ባለቤቶች",
    "home.how.title": "እንዴት ይሰራል",
    "home.how.step1": "ፈልግ እና አወዳድር",
    "home.how.step1.desc": "በፎቶ፣ ካርታ እና ልጽ ዋጋ የተረጋገጡ ዝርዝሮችን መልከቱ",
    "home.how.step2": "ቀጠሮ ያስይዙ",
    "home.how.step2.desc": "የመመልከቻ ቀጠሮ ይጠይቁ እና ከባለቤቱ ር በጥ ይወያዩ።",
    "home.how.step3": "ተሰማሩ",
    "home.how.step3.desc": "ዲጂታል ውል ፈርመው ቁልፎችን ይቀበሉ።",
    "home.featured.title": "ተመራጭ ቤቶች",
    "home.cta.title": "ባለቤት ነዎት?",
    "home.cta.desc": "ቤትዎን ያስቀምጡ እና ሺዎችን የተረጋጡ ተራዮችን ይድረሱ።",
    "home.cta.button": "ቤትዎን ያስቀምጡ",
    "home.getStarted": "ይጀምሩ",
    "home.quickTitle": "ትክክለኛ ቤት በፍጥነት ያግኙ",
    "home.location": "አድራሻ",
    "home.maxPrice": "ከፍተኛ ዋጋ",
    "home.bedrooms": "መኝታ ክፍሎች",
    "home.search": "ፈልግ",
    "home.whyTitle": "ለምን ይመርጣሉ?",
    "home.verified.title": "የተረጋገጡ ዝርዝሮች",
    "home.verified.desc":
      "እያንዳንዱ ቤት በፍለጋ ውጤቶች ውስጥ ከመታየቱ በፊት ለጥራት እና ለትክክለኛነት ይገመገማል።",
    "home.smart.title": "ብልህ ፍለጋ",
    "home.smart.desc":
      "እንደ ፍላጎትዎ ቤት ለማግኘት በዋጋ፣ በአድራሻ፣ በመኝታ ክፍሎች እና በተጨማሪ አገልግሎቶች ያጣሩ።",
    "home.secure.title": "አስተማማኝ ተሞክሮ",
    "home.secure.desc":
      "ለባለቤቶች እና ለተከራዮች አስተማማኝ መለያዎች፣ የተጠበቁ ዝርዝሮች እና ቀላል የቤት አስተዳደር።",

    // Auth
    "login.title": "ወደ መለያዎ ይግቡ",
    "login.subtitle": "ዳሽቦርድዎን፣ የተቀመጡ ቤቶችን እና ቀጠሮዎችን ይመልከቱ።",
    "login.forgot": "የይለፍ ቃል ረሱት?",
    "login.button": "ግባ",
    "login.loading": "በመግባት ላይ...",
    "login.noAccount": "መለያ የለዎትም?",
    "login.createOne": "ይመዝገቡ",
    "register.title": "መለያ ይፍጠሩ",
    "register.subtitle":
      "እንደ ተከራይ ወይም እንደ አከራይ ይመዝገቡ እና ኪራዮችን ማስተዳደር ይጀምሩ።",
    "register.tenant": "ተከራይ",
    "register.landlord": "አከራይ",
    "register.button": "መለያ ፍጠር",
    "register.loading": "በመመዝገብ ላይ...",
    "register.success": "ምዝገባው በተሳካ ሁኔታ ተጠናቋል!",
    "register.haveAccount": "መለያ አለዎት?",
    "register.logIn": "ይግቡ",
    "form.email": "ኢሜይል",
    "form.password": "የይለፍ ቃል",
    "form.fullName": "ሙሉ ስም",
    "form.phone": "ስልክ ቁጥር",
    "forgot.title": "የይለፍ ቃል ረሱት",
    "forgot.button": "የመመለሻ አገናኝ ላክ",
    "forgot.devLink": "የልማት አገናኝ:",
    "reset.title": "የይለፍ ቃል መለወጫ",
    "reset.newPassword": "አዲስ የይለፍ ቃል",
    "reset.button": "የይለፍ ቃል ቀይር",
    "verify.title": "ኢሜይል ማረጋገጫ",

    // Properties list
    "properties.title": "ያሉ ቤቶች",
    "properties.searchPlaceholder": "በስም፣ በከተማ፣ በአካባቢ ይፈልጉ...",
    "properties.allTypes": "ሁሉም አይነቶች",
    "properties.anyBedrooms": "ማንኛውም መኝታ",
    "properties.bedroomsMin": "መኝታ ክፍሎች",
    "properties.sort.newest": "አዲስ መጀመሪያ",
    "properties.sort.oldest": "አሮጌ መጀመሪያ",
    "properties.sort.priceAsc": "ዋጋ፦ ከዝቅ ወደ ከፍ",
    "properties.sort.priceDesc": "ዋጋ፦ ከከፍ ወደ ዝቅ",
    "properties.minPrice": "ዝቅተኛ ዋጋ (ብር)",
    "properties.maxPrice": "ከፍተኛ ዋጋ (ብር)",
    "properties.search": "ፈልግ",
    "properties.reset": "አጽዳ",
    "properties.found": "ቤቶች ተገኝተዋል",
    "properties.foundOne": "ቤት ተገኝቷል",
    "properties.none": "ምንም ቤቶች አልተገኙም።",
    "properties.prev": "ቀዳሚ",
    "properties.next": "ቀጣይ",
    "properties.viewDetails": "ዝርዝር ተመልከት",
    "properties.edit": "አስተካክል",
    "properties.delete": "ሰርዝ",
    "properties.rented": "ተከራይቷል",
    "properties.confirmDelete": "እርግጠኛ ነዎት ይህን ቤት መሰረዝ ይፈልጋሉ?",

    // Property types
    "type.Apartment": "አፓርታማ",
    "type.Villa": "ቪላ",
    "type.House": "ቤት",
    "type.Studio": "ስቱዲዮ",
    "type.Condominium": "ኮንዶሚኒየም",
    "type.Office": "ቢሮ",
    "type.Commercial Space": "የንግድ ቦታ",
    "type.Hostel": "ሆስቴል",
    "type.Shared Room": "የጋራ ክፍል",
    "type.Guest House": "የእንግዳ ቤት",

    // Property details
    "details.bedrooms": "መኝታ ክፍሎች",
    "details.bathrooms": "ባኞ ክፍሎች",
    "details.area": "ስፋት",
    "details.description": "መግለጫ",
    "details.amenities": "ተጨማሪ አገልግሎቶች",
    "details.ownerInfo": "የባለቤት መረጃ",
    "details.name": "ስም",
    "details.email": "ኢሜይል",
    "details.phone": "ስልክ",
    "details.verified": "የተረጋገጠ",
    "details.contactOwner": "ባለቤቱን ያነጋግሩ",
    "details.contactPlaceholder": "ለባለቤቱ መልዕክትዎን ይጻፉ...",
    "details.send": "ላክ",
    "details.messageSent": "መልዕክቱ ለባለቤቱ ተልኳል።",
    "details.report": "ንብረት ሪፖርት አድርግ",
    "details.selectReason": "ምክንያት ይምረጡ",
    "details.reasonFake": "የውሸት ንብረት",
    "details.reasonIncorrect": "የተሳሳተ መረጃ",
    "details.reasonFraud": "ተንኮለኛ ባለቤት",
    "details.reasonScam": "ስካም",
    "details.reasonInappropriate": "ያልተገባ ይዘት",
    "details.reasonOther": "ሌላ",
    "details.reportPlaceholder": "ችግሩን ይግለጹ (አማራጭ)",
    "details.submitReport": "ሪፖርት አስገባ",
    "details.reportSuccess": "ሪፖርቱ ገብቷል። ቡድናችን ይመረምረዋል።",
    "details.mapLocation": "የካርታ አካባቢ",
    "details.perMonth": "/ወር",
    "details.requestViewing": "ለመመልከት ቀጠሮ ይጠይቁ",
    "details.messagePlaceholder": "ለባለቤቱ መልዕክት (አማራጭ)",
    "details.sendRequest": "ቀጠሮ ላክ",
    "details.ownProperty": "ይህ የእርስዎ ቤት ነው።",
    "details.editIt": "ያስተካክሉት",
    "details.orManage": "ወይም የመመልከቻ ጥያቄዎችን ያስተዳድሩ በ",
    "details.bookingsPage": "የቀጠሮ ገጽ",
    "details.reviews": "ግምገማዎች",
    "details.writeReview": "ግምገማ ይጻፉ",
    "details.reviewPlaceholder": "ስለዚህ ቤት ያለዎትን ተሞክሮ ያካፍሉ...",
    "details.submitReview": "ግምገማ ላክ",
    "details.delete": "ሰርዝ",
    "details.save": "አስቀምጥ",
    "details.saved": "ተቀምጧል",
    "details.noReviews": "እስካሁን ግምገማ የለም። የመጀመሪያውን ይጻፉ!",
    "details.loginTo": "ይግቡ",
    "details.loginToDesc": "ግምገማ ለመጻፍ ወይም ቀጠሮ ለመጠየቅ።",
    "details.notFound": "ቤቱ አልተገኘም።",

    // Amenities
    "amenity.Furnished": "ዕቃ የተሞላ",
    "amenity.Parking": "መኪና ማቆሚያ",
    "amenity.Internet": "ኢንተርኔት",
    "amenity.Balcony": "በረንዳ",
    "amenity.Garden": "አትክልት",
    "amenity.Swimming Pool": "መዋኛ ገንዳ",
    "amenity.Security": "ደህንነት",
    "amenity.Pets Allowed": "እንስሳት ይፈቀዳል",

    // Add / Edit property
    "add.title": "ቤት ጨምር",
    "add.propertyTitle": "የቤት ርዕስ",
    "add.description": "መግለጫ",
    "add.price": "ዋጋ",
    "add.location": "አድራሻ",
    "add.bedrooms": "መኝታ ክፍሎች",
    "add.bathrooms": "ባኞ ክፍሎች",
    "add.area": "ስፋት (ካ.ሜ)",
    "add.propertyType": "የቤት አይነት",
    "add.photos": "ፎቶዎች (እስከ 5)",
    "add.button": "ቤት ጨምር",
    "add.uploading": "ፎቶዎች በመስቀል ላይ...",
    "add.saving": "ቤቱ በመቀመጥ ላይ...",
    "add.success": "ቤቱ በተሳካ ሁኔታ ተጨምሯል!",
    "edit.title": "ቤት አስተካክል",
    "edit.button": "ለውጦችን አስቀምጥ",
    "edit.success": "ቤቱ በተሳካ ሁኔታ ተዘምኗል!",

    // My properties
    "my.title": "የእኔ ቤቶች",
    "my.empty": "እስካሁን ምንም ቤቶች አልጨመሩም።",
    "my.confirmDelete": "ይህን ቤት መሰረዝ ይፈልጋሉ?",

    // Dashboard
    "dash.title": "ዳሽቦርድ",
    "dash.welcome": "እንኳን ደህና መጡ",
    "dash.email": "ኢሜይል",
    "dash.role": "ሚና",
    "dash.overview": "አጠቃላይ እይታ",
    "dash.favorites": "የተቀመጡ ተወዳጆች",
    "dash.viewingRequests": "የመመልከቻ ጥያቄዎች",
    "dash.myProperties": "የእኔ ቤቶች",
    "dash.pendingRequests": "በመጠበቅ ላይ ያሉ ጥያቄዎች",
    "dash.reviewsWritten": "የተጻፉ ግምገማዎች",
    "dash.loadingStats": "መረጃ በመጫን ላይ...",
    "dash.adminOverview": "የአስተዳዳሪ እይታ",
    "dash.totalUsers": "ጠቅላላ ተጠቃሚዎች",
    "dash.landlords": "አከራዮች",
    "dash.activeProperties": "ንቁ / ጠቅላላ ቤቶች",
    "dash.totalReviews": "ጠቅላላ ግምገማዎች",
    "dash.pendingViewings": "በመጠበቅ ላይ ያሉ ቀጠሮዎች",
    "dash.recentUsers": "አዲስ ተጠቃሚዎች",
    "dash.name": "ስም",
    "dash.joined": "የተመዘገበበት",
    "dash.notLoggedIn": "አልገቡም።",
    "dash.quickActions": "ፈጣን ርጊች",
    "dash.yourProperties": "የእርስዎ ቤቶች",
    "dash.manageAll": "ሁሉንም አስተዳድር",
    "dash.noProperties": "እስካሁን ንም ት አላስቀመጡም።",
    "dash.pendingApproval": "ፀድቅ በመጠበቅ ላይ",
    "dash.viewRequests": "የቀጠሮ ያቄችን ይመልከቱ",
    "dash.recentRequests": "የቅር የመመልከቻ ያቄች",
    "dash.viewAll": "ሁሉንም ይመልከ",
    "dash.noRequests": "እስካሁን የመመልከቻ ጥያ የሎትም",
    "dash.recommended": "ለእርስዎ የተመረጡ",

    // Bookings
    "bookings.title": "የመመልከቻ ቀጠሮዎች",
    "bookings.myRequests": "የእኔ ጥያቄዎች",
    "bookings.receivedRequests": "የደረሱ ጥያቄዎች",
    "bookings.none": "እስካሁን ምንም የመመልከቻ ጥያቄ አላደረጉም።",
    "bookings.browse": "ቤቶችን ይመልከቱ",
    "bookings.noneReceived": "በቤቶችዎ ላይ እስካሁን ምንም ጥያቄ አልደረሰም።",
    "bookings.cancel": "ሰርዝ",
    "bookings.approve": "አጽድቅ",
    "bookings.reject": "ውድቅ አድርግ",
    "bookings.requestedBy": "ጥያቄ ያቀረበው",
    "bookings.owner": "ባለቤት",
    "bookings.propertyRemoved": "ቤቱ ተሰርዟል",
    "status.pending": "በመጠበቅ ላይ",
    "status.approved": "ጸድቋል",
    "status.rejected": "ውድቅ ሆኗል",
    "status.cancelled": "ተሰርዟል",

    // Favorites
    "favorites.title": "የእኔ ተወዳጆች",
    "favorites.empty": "እስካሁን ምንም ቤቶች አላስቀመጡም።",

    // Messages
    "messages.title": "መልእክቶች",
    "messages.loading": "በመጫን ላይ...",
    "messages.empty": "እስካሁን ምንም ንብረቶች የሉም።",
    "messages.unread": "አዲስ",
    "messages.placeholder": "መልእክት ይጻፉ...",
    "messages.send": "ላክ",

    // Admin
    "admin.users": "ተጠቃሚዎችን ያስተዳድሩ",
    "admin.properties": "ንብረቶችን ያስተዳድሩ",
    "admin.reports": "ሪፖርቶች",
    "admin.searchUsers": "በስም ወይም በኢሜይል ፈልግ",
    "admin.allRoles": "ሁሉም ሚናዎች",
    "admin.allStatuses": "ሁሉም ሁኔታዎች",
    "admin.filter": "አጣራ",
    "admin.status": "ሁኔታ",
    "admin.actions": "እርምጃዎች",
    "admin.active": "ንቁ",
    "admin.suspended": "ታግዷል",
    "admin.suspend": "አቁም",
    "admin.activate": "አንቃ",
    "admin.delete": "ሰርዝ",
    "admin.deleteConfirm": "ተጠቃሚውን ሰርዝ",
    "admin.deletePropertyConfirm": "ይህን ንብረት ለመሰረዝ እርግጠኛ ነዎት?",
    "admin.approve": "ፍቀድ",
    "admin.markPending": "በመጠባበቅ ላይ",
    "admin.deactivate": "አሰናክል",
    "admin.inactive": "ያልነቃ",
    "admin.title": "ርዕስ",
    "admin.owner": "ባለቤት",
    "admin.price": "ዋጋ",
    "admin.noReports": "እስካሁን ምንም ሪፖርት አልቀረበም።",
    "admin.reportedBy": "ሪፖርት ያቀረበው",
    "admin.property": "ንብረት",
    "admin.user": "ተጠቃሚ",
    "admin.reason": "ምክንያት",
    "admin.resolve": "ፍታ",
    "admin.dismiss": "ውድቅ አድርግ",

    // Notifications
    "notifications.title": "ማሳወቂያዎች",
    "notifications.markAll": "ሁሉንም እንደተነበቡ ምልክት አድርግ",
    "notifications.empty": "እስካሁን ምንም ማሳወቂያዎች የሉም።",

    // Payments
    "payments.viewFirst": "መጀመሪያ የክፍያውን ቅጽበታዊ ገጽ ምስል መልከ",
    "payments.pageTitle": "ክፍያዎች",
    "payments.myMethods": "የክፍያ ዘዴቼ",
    "payments.methodsHint": "ተከራዮች በእነዚህ መለያዎች ከፍለው ቅበታዊ ገጽ ምስል ይልካሉ።",
    "payments.addMethod": "ዘዴ ጨምር",
    "payments.saveMethods": "ዘዴችን አስቀምጥ",
    "payments.methodsSaved": "የክፍያ ዘዴዎች ተቀምዋል።",
    "payments.labelPh": "መለያ (ለምሳሌ Telebirr)",
    "payments.accountName": "መለያ / ባለቤት ስም",
    "payments.accountNumber": "መለያ / ስልክ ቁር",
    "payments.received": "የተቀበሉ ክፍያዎች",
    "payments.myPayments": "ክፍያዎቼ",
    "payments.noPayments": "እስካሁን ክፍያ የለም።",
    "payments.approve": "አጽድቅ",
    "payments.reject": "ውድቅ አድርግ",
    "payments.rejectReason": "የውድቅ ክንያት (አማራጭ)",
    "payments.viewShot": "ማስረጃ ይመልከቱ",
    "payments.pendingApproval": "የባለቤት ፈቃድ በመጠበቅ ላይ",
    "payments.noMethods": "ባለቤቱ እስካሁን የክፍያ ዴ አላለም",
    "payments.uploadShot": "የክያ ቅበታዊ ጽ ምስል (ማስረጃ)",
    "payments.submitProof": "የክፍያ ማስረጃ ላክ",
    "payments.submitted": "የክፍያ ማስረጃ ተልል፤ የባለቤት ቃድ በመጠበ ላይ",
    "payments.needShot": "እባክዎ የክፍያ ቅጽበዊ ገጽ ምስል ያያይዙ።",
    "payments.payNow": "አሁን ክፈል",
    "payments.title": "ክፍያ አጠናቅቅ",
    "payments.method": "የክፍያ ዘዴ",
    "payments.bankTransfer": "የባንክ ዝውውር",
    "payments.card": "የካርድ ክፍያ",
    "payments.cash": "ጥሬ ገንዘብ",
    "payments.confirm": "ክፍያ አረጋግጥ",
    "payments.cancel": "ሰርዝ",
    "payments.success": "ክፍያው ተሳክቷል!",

    // Agreement
    "agreement.view": "ውል ይመልከቱ",
    "agreement.title": "የኪራይ ውል",
    "agreement.print": "አትም",
    "agreement.generated": "የተዘጋጀው",
    "agreement.tenant": "ተከራይ",
    "agreement.landlord": "አከራይ",
    "agreement.property": "ንብረት",
    "agreement.terms": "ዉሎች እና ሁኔታዎች",
    "agreement.startDate": "የመጀመሪያ ቀን",
    "agreement.monthlyRent": "ወርሃዊ ኪራይ",
    "agreement.deposit": "ተቀማጭ ገንዘብ",
    "agreement.tenantSignature": "የተከራይ ፊርማ",
    "agreement.landlordSignature": "የአከራይ ፊርማ",

    // Profile
    "profile.title": "የእርስዎ መገለጫ",
    "profile.address": "አድራሻ",
    "profile.bio": "አጭር መግለጫ",
    "profile.avatar": "የመገለጫ ምስል",
    "profile.save": "አስቀምጥ",
    "profile.cancel": "ተመለስ",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("lang") || "en"
  );

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  function t(key) {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }

  function toggleLang() {
    setLang((current) => (current === "en" ? "am" : "en"));
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLang() {
  return useContext(LanguageContext);
}
